#!/usr/bin/env bash

#ddev-generated
## Description: Helper function for Alloy
## Usage: alloy
## Example: "ddev alloy", "ddev alloy --reload"

# Open Alloy in preferred browser.
launch () {
  ddev launch :12345
}

# Send a request to reload configuration.
reloadConfig() {
  curl -X POST "${DDEV_PRIMARY_URL}:12345/-/reload"
}

while [ $# -gt 0 ]; do
  case "$1" in
  -r | --reload)
    reloadConfig
    exit 0;
    ;;
  esac
  shift
done

launch
