#!/usr/bin/env bash

#ddev-generated
## Description: Launch the grafana website
## Usage: grafana
## Example: "ddev grafana"

source .ddev/.env

PORT="${GRAFANA_HTTPS_PORT:-3000}"

# Open Grafana in preferred browser.
launch () {
  ddev launch :"${PORT}"
}

# Send a request to reload configuration.
reloadConfig() {
  ddev exec curl  -X POST "admin:admin@grafana:${PORT}/api/admin/provisioning/dashboards/reload"
  ddev exec curl  -X POST "admin:admin@grafana:${PORT}/api/admin/provisioning/datasources/reload"
  ddev exec curl  -X POST "admin:admin@grafana:${PORT}/api/admin/provisioning/plugins/reload"
  ddev exec curl  -X POST "admin:admin@grafana:${PORT}/api/admin/provisioning/alerting/reload"
}

while [ $# -gt 0 ]; do
  case "$1" in
  -r | --reload)
    reloadConfig
    exit 0;
    ;;
  esac
  shift
done

launch
