##ddev-generated
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: ddev-${DDEV_SITENAME}-node-exporter
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "/:/host:ro"
    command:
      - '--path.rootfs=/host'
      - '--path.udev.data=/host/run/udev/data'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|mnt/wsl|run/user)($|/)'
      - '--web.listen-address=:${NODE_EXPORTER_HTTP_PORT:-9100}'
