##ddev-generated
services:
  nginx-exporter:
    container_name: ddev-${DDEV_SITENAME}-nginx-exporter
    image: nginx/nginx-prometheus-exporter:1.4.2
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
    environment:
      - HTTPS_EXPOSE=9113:9113
    command: --nginx.scrape-uri=http://web:8080/stub_status

  web:
    # Expose the port that we scrape above.
    environment:
      - HTTP_EXPOSE=8080:8080
    # Create the scrape URI
    volumes:
      - ./nginx_full/stub_status.conf:/etc/nginx/conf.d/stub_status.conf
