##ddev-generated

# Postgres Exporter
# This file configures Prometheus for Postgres Exporter. Metrics are prefixed with `pg`.
# @See https://github.com/prometheus-community/postgres_exporter

scrape_configs:
  # Get hardware and OS metrics exposed by *NIX kernels
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
