##ddev-generated

# MySQL Exporter
# This file configures Prometheus for MySQL-exporter. Metrics are prefixed with `mysql`.
# @See https://github.com/prometheus/mysqld_exporter

scrape_configs:
  - job_name: mysql
    metrics_path: /probe
    params:
      # Not required. Will match value to child in config file. Default value is `client`.
      auth_module: [client.servers]
    static_configs:
      - targets:
        # All mysql hostnames or unix sockets to monitor.
        - db:3306
        # Uncomment to target unix sockets.
        # - unix:///run/mysqld/mysqld.sock
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # The mysqld_exporter host:port
        replacement: mysql-exporter:9104
