##ddev-generated
apiVersion: 1

datasources:
- name: Tempo
  uid: tempo
  type: tempo
  access: proxy
  url: http://grafana-tempo:3200
  basicAuth: false
  jsonData:
    httpMethod: GET
    tracesToMetrics:
      datasourceUid: 'prometheus'
    serviceMap:
        datasourceUid: 'Prometheus'
      datasourceUid: 'prometheus'
    tracesToLogsV2:
      datasourceUid: 'loki'
