{
 "title": "MySQL",
 "description": "Percona Monitoring and Management プロジェクトからのダッシュボード。",
 "tags": [
  "mysql",
  "db",
  "prometheus"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "間隔", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "ホスト",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL アップタイム",
   "type": "stat",
   "description": "**MySQL アップタイム**\n\nMySQL サーバープロセスの最後の再起動からの経過時間。",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "現在の QPS",
   "type": "stat",
   "description": "**現在の QPS**\n\nMySQL の ``SHOW STATUS`` コマンドで報告されたクエリに基づき、サーバーが直近 1 秒間に実行したステートメント数です。この変数は Questions 変数とは異なり、ストアドプログラム内で実行されたステートメントも含みます。\n``COM_PING`` や ``COM_STATISTICS`` コマンドはカウントされません。",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "InnoDB バッファプールサイズ",
   "type": "stat",
   "description": "**InnoDB バッファプールサイズ**\n\nInnoDB はデータやインデックスをメモリにキャッシュするためのバッファプール領域を維持します。バッファプールを活用して頻繁にアクセスされるデータをメモリに保持することが、MySQL チューニングの最も重要な側面の一つです。ワーキングセットをメモリ内に収めることが目標です。多くの場合、専用データベースホストの利用可能メモリの 60%-90% の範囲が推奨されますが、多くの要因によります。",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "接続",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL 接続数",
     "type": "timeseries",
     "description": "**最大接続数**\n\n最大接続数は同時クライアント接続の最大許可数です。デフォルトは 151 です。この値を増やすと mysqld が必要とするファイルディスクリプタ数も増加します。必要なディスクリプタ数が利用できない場合、サーバーは最大接続数の値を減らします。\n\nmysqld は実際には最大接続数 + 1 のクライアント接続を許可します。この追加の接続は root など SUPER 権限を持つアカウント用に予約されています。\n\n最大使用接続数は、サーバー起動後に同時に使用された接続数の最大値です。\n\n接続数は MySQL サーバーへの接続試行回数（成功・失敗問わず）です。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$host\"} )",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "MySQL クライアントスレッドアクティビティ",
     "type": "timeseries",
     "description": "**MySQL アクティブスレッド**\n\nThreads Connected はオープン接続数、Threads Running はスリープしていないスレッド数です。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[5m])",
       "legendFormat": "Peak Threads Connected"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
       "legendFormat": "Peak Threads Running"
      },
      {
       "expr": "avg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
       "legendFormat": "Avg Threads Running"
      }
     ]
    }
   ]
  },
  { "title": "テーブルロック", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "MySQL Questions",
   "type": "timeseries",
   "description": "**MySQL Questions**\n\nサーバーが実行したステートメント数です。これはクライアントからサーバーに送信されたステートメントのみを含み、QPS 計算で使われる Queries とは異なり、ストアドプログラム内で実行されたステートメントは含みません。\n\n以下のコマンドはカウントされません:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_questions{instance=\"$host\"}[5m])",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "MySQL スレッドキャッシュ",
   "type": "timeseries",
   "description": "**MySQL スレッドキャッシュ**\n\nthread_cache_size 変数は、サーバーが再利用のためにキャッシュすべきスレッド数を設定します。クライアントが切断されると、キャッシュが満杯でなければそのクライアントのスレッドがキャッシュに入ります。MySQL 5.6.8 以降では自動サイズ（最大 100 まで）です。スレッド要求はキャッシュから再利用され、キャッシュが空の場合のみ新しいスレッドが作成されます。\n\n* *Threads_created*: 接続処理のために作成されたスレッド数。\n* *Threads_cached*: スレッドキャッシュ内のスレッド数。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_thread_cache_size{instance=\"$host\"}",
     "legendFormat": "Thread Cache Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_cached{instance=\"$host\"}",
     "legendFormat": "Threads Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_threads_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_threads_created{instance=\"$host\"}[5m])",
     "legendFormat": "Threads Created"
    }
   ]
  },
  {
   "title": "ソート",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL ソート",
     "type": "timeseries",
     "description": "**MySQL ソート**\n\nクエリの構造や順序などの要件により、MySQL は返す前に行をソートします。例えば、テーブルが 1 から 10 で並んでいても、逆順で結果が必要な場合、MySQL は 10 から 1 へとソートします。\n\nこのグラフは、全テーブルや特定範囲のスキャンが必要だったソートや、インデックスでソートできなかったケースも示します。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_rows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_rows{instance=\"$host\"}[5m])",
       "legendFormat": "Sort Rows"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_range{instance=\"$host\"}[5m])",
       "legendFormat": "Sort Range"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[5m])",
       "legendFormat": "Sort Merge Passes"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_sort_scan{instance=\"$host\"}[$interval]) or irate(mysql_global_status_sort_scan{instance=\"$host\"}[5m])",
       "legendFormat": "Sort Scan"
      }
     ]
    },
    {
     "title": "MySQL スロークエリ",
     "type": "timeseries",
     "description": "**MySQL スロークエリ**\n\nスロークエリは long_query_time 設定より遅いクエリとして定義されます。例えば long_query_time が 3 の場合、3 秒以上かかるクエリがこのグラフに表示されます。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_slow_queries{instance=\"$host\"}[$interval]) or irate(mysql_global_status_slow_queries{instance=\"$host\"}[5m])",
       "legendFormat": "Slow Queries"
      }
     ]
    }
   ]
  },
  {
   "title": "アボート",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL アボートされた接続",
     "type": "timeseries",
     "description": "**アボートされた接続**\n\n特定ホストが MySQL に接続し、途中で接続が中断された場合（例: 認証失敗）、MySQL はその情報をシステムテーブルに保持します（5.6 以降は performance_schema で公開）。\n\n成功しないリクエストが max_connect_errors の値に達すると、mysqld は問題があると判断し、そのホストからの接続をブロックします。\n\n再度接続を許可するには ``FLUSH HOSTS`` ステートメントを実行してください。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_connects{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_connects{instance=\"$host\"}[5m])",
       "legendFormat": "Aborted Connects (attempts)"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_aborted_clients{instance=\"$host\"}[$interval]) or irate(mysql_global_status_aborted_clients{instance=\"$host\"}[5m])",
       "legendFormat": "Aborted Clients (timeout)"
      }
     ]
    },
    {
     "title": "MySQL テーブルロック",
     "type": "timeseries",
     "description": "**テーブルロック**\n\nMySQL は様々な理由で複数種類のロックを取得します。このグラフでは、MySQL がストレージエンジンから要求したテーブルレベルのロック数を示します。InnoDB の場合、多くは実際には行ロックですが、特定の場合のみテーブルロックを取得します。\n\nLocks Immediate と Locks Waited を比較するのが有用です。Locks Waited が増加していればロック競合が発生しています。Locks Immediate の増減は通常の動作です。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[5m])",
       "legendFormat": "Table Locks Immediate"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_table_locks_waited{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_locks_waited{instance=\"$host\"}[5m])",
       "legendFormat": "Table Locks Waited"
      }
     ]
    }
   ]
  },
  {
   "title": "ネットワーク",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL ネットワークトラフィック",
     "type": "timeseries",
     "description": "**MySQL ネットワークトラフィック**\n\nここでは MySQL によって生成されたネットワークトラフィック量を確認できます。Outbound は MySQL から送信されたトラフィック、Inbound は MySQL が受信したトラフィックです。",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_received{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_bytes_sent{instance=\"$host\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "MySQL ネットワーク使用量（毎時）",
     "type": "timeseries",
     "description": "**MySQL ネットワーク使用量（毎時）**\n\nここでは MySQL によって 1 時間ごとに生成されたネットワークトラフィック量を確認できます。棒グラフで送信データと受信データを比較できます。",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_received{instance=\"$host\"}[1h])",
       "legendFormat": "Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_bytes_sent{instance=\"$host\"}[1h])",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  { "title": "メモリ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "MySQL 内部メモリ概要",
   "type": "timeseries",
   "description": "***システムメモリ***: システム全体のメモリ。\\\n***InnoDB バッファプールデータ***: InnoDB はデータやインデックスをメモリにキャッシュするためのバッファプール領域を維持します。\\\n***TokuDB キャッシュサイズ***: InnoDB バッファプールと同様に、TokuDB はインストール済み RAM の 50% を自身のキャッシュに割り当てます。\\\n***キー バッファサイズ***: MYISAM テーブルのインデックスブロックがバッファされ、全スレッドで共有されます。key_buffer_size はインデックスブロック用バッファのサイズです。\\\n***アダプティブハッシュインデックスサイズ***: InnoDB が特定のインデックス値へのアクセス頻度が高いと判断した場合、B-Tree インデックス上にハッシュインデックスをメモリ上に構築します。\\\n***クエリキャッシュサイズ***: クエリキャッシュは SELECT 文のテキストとクライアントに送信された結果を保存します。クエリキャッシュはスケーラビリティに問題があり、同時に 1 スレッドしか操作できません。\\\n***InnoDB ディクショナリサイズ***: データディクショナリは InnoDB の内部カタログです。InnoDB はディクショナリをディスクに保存し、サーバー稼働中にメモリへロードします。\\\n***InnoDB ログバッファサイズ***: MySQL InnoDB ログバッファにより、トランザクションはコミット前にログをディスクへ書き込まずに実行できます。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}",
     "legendFormat": "System Memory"
    },
    {
     "expr": "mysql_global_status_innodb_page_size{instance=\"$host\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{instance=\"$host\"}",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_variables_query_cache_size{instance=\"$host\"}",
     "legendFormat": "Query Cache Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{instance=\"$host\"}",
     "legendFormat": "Adaptive Hash Index Size"
    },
    {
     "expr": "mysql_global_variables_tokudb_cache_size{instance=\"$host\"}",
     "legendFormat": "TokuDB Cache Size"
    }
   ]
  },
  { "title": "クエリキャッシュ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "MySQL クエリキャッシュメモリ",
   "type": "timeseries",
   "description": "**MySQL クエリキャッシュメモリ**\n\nクエリキャッシュはスケーラビリティに大きな問題があり、同時に 1 スレッドしか操作できません。これは SELECT だけでなく、INSERT/UPDATE/DELETE でも同様です。\n\nまた、`query_cache_size` を大きくすると操作が遅くなります。並列環境ではクエリキャッシュが競合ポイントとなり、パフォーマンスが低下します。MariaDB や AWS Aurora では競合解消のための改良が行われていますが、MySQL 8.0 ではクエリキャッシュ機能自体が廃止されています。\n\nほとんどの環境での推奨設定は以下です:\n  ``query_cache_type=0``\n  ``query_cache_size=0``\n\nこれらの値は動的に変更できますが、競合ポイントを完全に排除するにはデータベースの再起動が必要です。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_free_memory{instance=\"$host\"}",
     "legendFormat": "Free Memory"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_query_cache_size{instance=\"$host\"}",
     "legendFormat": "Query Cache Size"
    }
   ]
  },
  {
   "title": "MySQL クエリキャッシュアクティビティ",
   "type": "timeseries",
   "description": "**MySQL クエリキャッシュアクティビティ**\n\nクエリキャッシュはスケーラビリティに大きな問題があり、同時に 1 スレッドしか操作できません。これは SELECT だけでなく、INSERT/UPDATE/DELETE でも同様です。\n\nまた、`query_cache_size` を大きくすると操作が遅くなります。並列環境ではクエリキャッシュが競合ポイントとなり、パフォーマンスが低下します。MariaDB や AWS Aurora では競合解消のための改良が行われていますが、MySQL 8.0 ではクエリキャッシュ機能自体が廃止されています。\n\nほとんどの環境での推奨設定は以下です:\n``query_cache_type=0``\n``query_cache_size=0``\n\nこれらの値は動的に変更できますが、競合ポイントを完全に排除するにはデータベースの再起動が必要です。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_hits{instance=\"$host\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_inserts{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_inserts{instance=\"$host\"}[5m])",
     "legendFormat": "Inserts"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_not_cached{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_not_cached{instance=\"$host\"}[5m])",
     "legendFormat": "Not Cached"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_qcache_lowmem_prunes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_qcache_lowmem_prunes{instance=\"$host\"}[5m])",
     "legendFormat": "Prunes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_qcache_queries_in_cache{instance=\"$host\"}",
     "legendFormat": "Queries in Cache"
    }
   ]
  },
  { "title": "ファイルとテーブル", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "MySQL ファイルオープン数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_files{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_files{instance=\"$host\"}[5m])",
     "legendFormat": "Openings"
    }
   ]
  },
  {
   "title": "MySQL オープンファイル数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_files{instance=\"$host\"}",
     "legendFormat": "Open Files"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_open_files_limit{instance=\"$host\"}",
     "legendFormat": "Open Files Limit"
    },
    {
     "expr": "mysql_global_status_innodb_num_open_files{instance=\"$host\"}",
     "legendFormat": "InnoDB Open Files"
    }
   ]
  },
  { "title": "テーブルオープン数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MySQL テーブルオープンキャッシュステータス",
   "type": "timeseries",
   "description": "**MySQL テーブルオープンキャッシュステータス**\n\n`table_open_cache_instances` は仮想 CPU 数に緩やかに合わせて設定することが推奨されます。インスタンス数が多いほどキャッシュが分割されます。例えばキャッシュが 500 でインスタンスが 10 の場合、各キャッシュは 50 ずつしか保持できません。\n\n`table_definition_cache` と `table_open_cache` は MySQL 5.6 以降自動サイズなので、デフォルトのままで問題ありません（値を設定しない）。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_opened_tables{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_tables{instance=\"$host\"}[5m])",
     "legendFormat": "Openings"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[5m])",
     "legendFormat": "Misses due to Overflows"
    },
    {
     "expr": "(rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))/((rate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m]))+(rate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[$interval]) or irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])))",
     "legendFormat": "Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL オープンテーブル数",
   "type": "timeseries",
   "description": "**MySQL オープンテーブル数**\n\n`table_open_cache_instances` は仮想 CPU 数に緩やかに合わせて設定することが推奨されます。インスタンス数が多いほどキャッシュが分割されます。例えばキャッシュが 500 でインスタンスが 10 の場合、各キャッシュは 50 ずつしか保持できません。\n\n`table_definition_cache` と `table_open_cache` は MySQL 5.6 以降自動サイズなので、デフォルトのままで問題ありません（値を設定しない）。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_tables{instance=\"$host\"}",
     "legendFormat": "Open Tables"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_open_cache{instance=\"$host\"}",
     "legendFormat": "Table Open Cache"
    }
   ]
  },
  { "title": "MySQL テーブル定義キャッシュ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "MySQL テーブル定義キャッシュ",
   "type": "timeseries",
   "description": "**MySQL テーブル定義キャッシュ**\n\n`table_open_cache_instances` は仮想 CPU 数に緩やかに合わせて設定することが推奨されます。インスタンス数が多いほどキャッシュが分割されます。例えばキャッシュが 500 でインスタンスが 10 の場合、各キャッシュは 50 ずつしか保持できません。\n\n`table_definition_cache` と `table_open_cache` は MySQL 5.6 以降自動サイズなので、デフォルトのままで問題ありません（値を設定しない）。",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_open_table_definitions{instance=\"$host\"}",
     "legendFormat": "Open Table Definitions"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_table_definition_cache{instance=\"$host\"}",
     "legendFormat": "Table Definitions Cache Size"
    },
    {
     "expr": "rate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_opened_table_definitions{instance=\"$host\"}[5m])",
     "legendFormat": "Opened Table Definitions"
    }
   ]
  }
 ]
}