{
 "title": "Nginx",
 "tags": [
  "web",
  "nginx",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "総リクエスト数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "総リクエスト数" }
   ]
  },
  {
   "title": "レスポンス",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "処理済み" },
    { "expr": "nginx_connections_waiting", "legendFormat": "待機中" }
   ]
  },
  {
   "title": "アクティビティ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nginx_connections_writing", "legendFormat": "書き込み中" },
    { "expr": "nginx_connections_reading", "legendFormat": "読み込み中" }
   ]
  },
  {
   "title": "エラーコード",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"200\"}",
     "legendFormat": "200"
    },
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"500\"}",
     "legendFormat": "500"
    },
    {
     "expr": "promhttp_metric_handler_requests_total{code=\"503\"}",
     "legendFormat": "503"
    }
   ]
  }
 ]
}