##ddev-generated
apiVersion: 1

datasources:
- name: Tempo
  uid: tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  basicAuth: false
  jsonData:
    tracesToMetrics:
      datasourceUid: 'Prometheus'
    serviceMap:
        datasourceUid: 'Prometheus'
