#ddev-generated
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    orgId: 1
    version: 1
    uid: prometheus
    access: proxy
    isDefault: true
    basicAuth: false
    editable: false
    jsonData:
      httpMethod: GET
