#ddev-generated

# Blackbox

scrape_configs:
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    metrics_path: '/metrics'
    static_configs:
      - targets: ['blackbox:9115']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://${DDEV_PRIMARY_UR}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
