#ddev-generated

# Node Exporter
# This file configures Prometheus for Node Exporter. Metrics are prefixed with `node`.
# @See https://github.com/prometheus/node_exporter

scrape_configs:
  # Get exposed Node metrics
  - job_name: 'node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']
